export const testCases: [markdown: string, html: string, name?: string][] = [
  ['paragraph', '<p>paragraph</p>'],
  ['> this is blockquote', '<blockquote><p>this is blockquote</p></blockquote>'],
  ['# heading 1', '<h1>heading 1</h1>'],
  ['## heading 2', '<h2>heading 2</h2>'],
  ['### heading 3', '<h3>heading 3</h3>'],
  ['#### heading 4', '<h4>heading 4</h4>'],
  ['##### heading 5', '<h5>heading 5</h5>'],
  ['###### heading 6', '<h6>heading 6</h6>'],
  ['---', '<hr />'],
  ['<div>bold: <b>bold</b></div>', '<div>bold: <b>bold</b></div>'],
  ['```\ncode\n```', '<pre class="language-text" data-lang="text" data-meta=""><code class="language-text" data-lang="text" data-meta="">code</code></pre>', 'plain text code block'],
  ['```js\nconsole.log(123);\n```', '<pre class="language-js" data-lang="js" data-meta=""><code class="language-js" data-lang="js" data-meta="">console.log(123);</code></pre>', 'code block with language'],
  ['```js meta\nconsole.log(123);\n```', '<pre class="language-js" data-lang="js" data-meta="meta"><code class="language-js" data-lang="js" data-meta="meta">console.log(123);</code></pre>', 'code block with language and meta'],
  ['- list item', '<ul><li>list item</li></ul>', 'unordered list item'],
  ['- list item\n  \nparagraph', '<ul><li><p>list item</p><p>paragraph</p></li></ul>', 'unordered list item (multiline)'],
  ['- list item\n- second list item', '<ul><li>list item</li><li>second list item</li></ul>', 'unordered list items'],
  ['- list item\n  - nested list item', '<ul><li><p>list item</p><ul><li>nested list item</li></ul></li></ul>', 'unordered list item with nested list item'],
  ['1. ordered list item', '<ol start="1"><li>ordered list item</li></ol>', 'ordered list item'],
  ['2. ordered list\n2. start from 2', '<ol start="2"><li>ordered list</li><li>start from 2</li></ol>', 'ordered list items'],
  ['- [x] checked list item\n- [ ] unchecked', '<ul><li data-checked="true">checked list item</li><li data-checked="false">unchecked</li></ul>', 'checked and unchecked list items'],
];
