export const testCases: [markdown: string, html: string, name?: string, inlineOnly?: boolean][] = [
  ['plain text', 'plain text'],
  ['*italic*', '<em>italic</em>'],
  ['*italic* and _also italic_', '<em>italic</em> and <em>also italic</em>'],
  ['**bold**', '<strong>bold</strong>'],
  ['**bold** and __also bold__', '<strong>bold</strong> and <strong>also bold</strong>'],
  ['`code`', '<code>code</code>'],
  ['~~strikethrough~~', '<del>strikethrough</del>'],
  ['||spoiler||', '<spoiler style="background:black;color:black">spoiler</spoiler>'],
  ['Reddit: >!spoiler!<', 'Reddit: <spoiler style="background:black;color:black">spoiler</spoiler>'],
  ['$$x + x$$', '<code class="language-math" data-lang="math">x + x</code>'],
  ['https://example.com', 'https://example.com'],
  ['x^2^', 'x<sup>2</sup>'],
  ['H~2~O', 'H<sub>2</sub>O'],
  ['==highlight==', '<mark>highlight</mark>'],
  ['++underline++', '<u>underline</u>'],
  ['a\\nb', 'a<br />b', 'explicit line break'],
  ['<i>html</i>', '<i>html</i>', 'inline html'],
];
